# Generated by Django 5.2.14 on 2026-05-24 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0006_evaluacioncategoria_periodoacademico_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacioncategoria',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='calificaciones.evaluacioncategoria'),
        ),
    ]
