# Generated by Django 5.2.14 on 2026-05-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0008_evaluacionrubrica_asignatura_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=150)),
                ('detalle', models.TextField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='incidencias/')),
                ('notificar', models.BooleanField(default=False)),
                ('incidencia_tipo', models.CharField(choices=[('COMPORTAMIENTO', 'Comportamiento'), ('ACADEMICO', 'Académico'), ('ASISTENCIAL', 'Asistencial')], default='ASISTENCIAL', max_length=20)),
            ],
        ),
    ]
