# Generated by Django 5.2.14 on 2026-05-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0009_incidencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notaCuantitativa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notaCualitativa', models.CharField(blank=True, max_length=100, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('id_EVA', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
