# Generated by Django 5.2.14 on 2026-05-26 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0010_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='calidicacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='calificaciones.calificacion'),
            preserve_default=False,
        ),
    ]
