# Generated by Django 5.2.14 on 2026-05-26 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0011_incidencia_calidicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionMejora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notaCuantitativa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notaCualitativa', models.CharField(blank=True, max_length=100)),
                ('observacion', models.TextField(blank=True)),
                ('calificacion_mejora_tipo', models.CharField(choices=[('REFUERZO', 'Refuerzo'), ('PEDAGOGICO', 'Pedagógico'), ('MEJORA', 'Mejora')], default='REFUERZO', max_length=20)),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mejoras', to='calificaciones.calificacion')),
            ],
        ),
    ]
