# Generated by Django 5.2.14 on 2026-05-26 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0012_calificacionmejora'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notaCuantitativa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notaCualitativa', models.CharField(blank=True, max_length=100)),
                ('observacion', models.TextField(blank=True)),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='calificaciones.calificacion')),
            ],
        ),
    ]
