# Generated by Django 5.2.14 on 2026-05-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0013_calificacionhistorico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promedio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notaCuantitativa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notaCualitativa', models.CharField(blank=True, max_length=100)),
                ('distributivo_asignatura_id', models.PositiveBigIntegerField()),
                ('matricula_id', models.PositiveBigIntegerField()),
            ],
        ),
    ]
