# Generated by Django 5.2.14 on 2026-05-26 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0014_promedio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromedioCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notaCuantitativa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notaCualitativa', models.CharField(max_length=255)),
                ('promedio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promedios_categoria', to='calificaciones.promedio')),
                ('promedio_categoria_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='calificaciones.promediocategoria')),
            ],
        ),
    ]
