# Generated by Django 5.2.14 on 2026-05-26 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0015_promediocategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='promedio_categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='calificaciones.promediocategoria'),
            preserve_default=False,
        ),
    ]
