# Generated by Django 5.2.14 on 2026-05-26 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0016_calificacion_promedio_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignaturaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('distributivo_asignatura_id', models.PositiveBigIntegerField()),
                ('entrega_id', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
