# Generated by Django 5.2.14 on 2026-05-26 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0017_asignaturaevaluacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignaturaevaluacion',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='asignaturaevaluacion',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='asignaturaevaluacion',
            name='entrega_id',
        ),
        migrations.RemoveField(
            model_name='asignaturaevaluacion',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='asignaturaevaluacion',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='asignaturaevaluacion',
            name='nombre',
        ),
        migrations.AddField(
            model_name='asignaturaevaluacion',
            name='evaluacion_categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas_evaluacion', to='calificaciones.evaluacioncategoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asignaturaevaluacion',
            name='promedio_categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas_evaluaciones', to='calificaciones.promediocategoria'),
            preserve_default=False,
        ),
    ]
