import React, { useState } from 'react';
import { ActionIconButton, EditEntityModal, EditIcon, FileInputField, TrashIcon } from '../../../components/EditEntityModal';
import type { AdaptacionCurricular, AdaptacionCurricularPlanificacion, AdaptacionEstado, CatalogItem } from '../../../types/entities/dece';

interface Props {
  adaptaciones: AdaptacionCurricular[];
  planificaciones: AdaptacionCurricularPlanificacion[];
  formOptions: { ESTADO_OPTIONS: AdaptacionEstado[]; distributivoAsignaturas: CatalogItem[]; getAdaptacionNombre: (id?: number | null, fallback?: string | null) => string; getDistributivoAsignaturaNombre: (id?: number | null, fallback?: string | null) => string };
  planificacionForm: any;
}
const fieldStyle: React.CSSProperties = { width: '100%', height: '42px', padding: '0 12px', borderRadius: '8px', border: '1px solid var(--outline-variant)', background: 'var(--surface)', color: 'var(--on-surface)', fontSize: 'var(--font-body-sm)' };
const labelStyle: React.CSSProperties = { display: 'block', marginBottom: '6px', fontSize: 'var(--font-body-sm)', fontWeight: 600, color: 'var(--on-surface)' };
const badgeStyle = (estado: string): React.CSSProperties => ({ display: 'inline-flex', padding: '4px 8px', borderRadius: '999px', background: estado === 'APROBADO' ? 'var(--primary-container)' : estado === 'ENVIADO' ? 'var(--secondary-container)' : 'var(--surface-container-high)', color: 'var(--on-surface)', fontSize: '11px', fontWeight: 700 });
const catalogLabel = (item: CatalogItem) => item.asignatura_ofertada_nombre || item.nombre || `Asignatura ${item.id}`;
type EditState = { id: number; adaptacion_curricular: string; distributivo_asignatura: string; archivo: File | null; comentario: string; estado: AdaptacionEstado };

export const TabAdaptacionPlanificacion: React.FC<Props> = ({ adaptaciones, planificaciones, planificacionForm, formOptions }) => {
  const [editing, setEditing] = useState<EditState | null>(null);
  const openEdit = (item: AdaptacionCurricularPlanificacion) => setEditing({ id: item.id, adaptacion_curricular: String(item.adaptacion_curricular ?? ''), distributivo_asignatura: String(item.distributivo_asignatura ?? ''), archivo: null, comentario: item.comentario ?? '', estado: item.estado });
  const acceptEdit = async () => { if (!editing || !planificacionForm.handleActualizarPlanificacion) return; if (await planificacionForm.handleActualizarPlanificacion(editing.id, editing)) setEditing(null); };
  const fields = (state: EditState, setState: (value: EditState) => void) => <>
    <div><label style={labelStyle}>Adaptación curricular</label><select value={state.adaptacion_curricular} onChange={(e) => setState({ ...state, adaptacion_curricular: e.target.value })} style={fieldStyle}><option value="">Seleccione...</option>{adaptaciones.map((a) => <option key={a.id} value={a.id}>{formOptions.getAdaptacionNombre(a.id)}</option>)}</select></div>
    <div><label style={labelStyle}>Asignatura del distributivo</label><select value={state.distributivo_asignatura} onChange={(e) => setState({ ...state, distributivo_asignatura: e.target.value })} style={fieldStyle}><option value="">Sin asignatura</option>{formOptions.distributivoAsignaturas.map((a) => <option key={a.id} value={a.id}>{catalogLabel(a)}</option>)}</select></div>
    <div><label style={labelStyle}>Estado</label><select value={state.estado} onChange={(e) => setState({ ...state, estado: e.target.value as AdaptacionEstado })} style={fieldStyle}>{formOptions.ESTADO_OPTIONS.map((e) => <option key={e} value={e}>{e}</option>)}</select></div>
    <div><label style={labelStyle}>Archivo PDF</label><FileInputField accept=".pdf,application/pdf" file={state.archivo} onChange={(file) => setState({ ...state, archivo: file })} /></div>
    <div><label style={labelStyle}>Comentario</label><input value={state.comentario} onChange={(e) => setState({ ...state, comentario: e.target.value })} placeholder="Ej. Requiere seguimiento mensual" style={fieldStyle} /></div>
  </>;
  return <div style={{ display: 'flex', flexDirection: 'column', gap: '20px', width: '100%' }}>
    <form onSubmit={planificacionForm.handleAgregarPlanificacion} style={{ background: 'var(--surface-container-lowest)', padding: '20px', borderRadius: '8px', border: '1px solid var(--outline-variant)', display: 'grid', gridTemplateColumns: 'repeat(3, minmax(0, 1fr))', gap: '16px', width: '100%', boxSizing: 'border-box' }}>{fields({ id: 0, adaptacion_curricular: planificacionForm.adaptacionCurricularPlanificacionId, distributivo_asignatura: planificacionForm.distributivoAsignaturaReferencia, archivo: planificacionForm.archivoPlanificacion, comentario: planificacionForm.comentarioPlanificacion, estado: planificacionForm.estadoPlanificacion }, (v) => { planificacionForm.setAdaptacionCurricularPlanificacionId(v.adaptacion_curricular); planificacionForm.setDistributivoAsignaturaReferencia(v.distributivo_asignatura); planificacionForm.setArchivoPlanificacion(v.archivo); planificacionForm.setComentarioPlanificacion(v.comentario); planificacionForm.setEstadoPlanificacion(v.estado); })}<div style={{ display: 'flex', gap: '8px', alignItems: 'flex-end', justifyContent: 'flex-end' }}><button type="submit" style={{ background: 'var(--primary)', color: 'var(--on-primary)', border: 'none', padding: '0 18px', borderRadius: '8px', fontWeight: 600, cursor: 'pointer', height: '42px', whiteSpace: 'nowrap' }}>+ Agregar</button></div></form>
    <div style={{ background: 'var(--surface-container-lowest)', borderRadius: '8px', border: '1px solid var(--outline-variant)', overflow: 'hidden', width: '100%' }}><div style={{ padding: '14px 20px', borderBottom: '1px solid var(--outline-variant)' }}><h3 style={{ margin: 0, fontSize: 'var(--font-body-sm)', color: 'var(--primary)', fontWeight: '700' }}>Planificaciones DECE</h3></div><table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left' }}><thead><tr style={{ background: 'var(--primary)', color: 'var(--on-primary)' }}><th style={{ padding: '12px 20px' }}>NRO</th><th style={{ padding: '12px 20px' }}>ADAPTACIÓN</th><th style={{ padding: '12px 20px' }}>ASIGNATURA</th><th style={{ padding: '12px 20px' }}>ESTADO</th><th style={{ padding: '12px 20px' }}>ARCHIVO</th><th style={{ padding: '12px 20px' }}>COMENTARIO</th><th style={{ padding: '12px 20px', textAlign: 'center' }}>ACCIONES</th></tr></thead><tbody>{planificaciones.length === 0 ? <tr><td colSpan={7} style={{ padding: '20px', textAlign: 'center', color: 'var(--on-surface-variant)' }}>No hay planificaciones registradas.</td></tr> : planificaciones.map((item, index) => <tr key={item.id} style={{ borderBottom: '1px solid var(--outline-variant)' }}><td style={{ padding: '12px 20px', color: 'var(--on-surface-variant)' }}>{(index + 1).toString().padStart(2, '0')}</td><td style={{ padding: '12px 20px', fontWeight: 600 }}>{formOptions.getAdaptacionNombre(item.adaptacion_curricular, item.adaptacion_nombre)}</td><td style={{ padding: '12px 20px' }}>{formOptions.getDistributivoAsignaturaNombre(item.distributivo_asignatura, item.distributivo_asignatura_nombre || item.distributivo_asignatura_referencia)}</td><td style={{ padding: '12px 20px' }}><span style={badgeStyle(item.estado)}>{item.estado}</span></td><td style={{ padding: '12px 20px' }}>{item.archivo ? <a href={item.archivo} target="_blank" rel="noreferrer">Ver PDF</a> : 'Sin archivo'}</td><td style={{ padding: '12px 20px', color: 'var(--on-surface-variant)' }}>{item.comentario}</td><td style={{ padding: '12px 20px', textAlign: 'center' }}><ActionIconButton label="Editar" icon={<EditIcon />} onClick={() => openEdit(item)} style={{ marginRight: '8px' }} /><ActionIconButton label="Eliminar" icon={<TrashIcon />} tone="danger" onClick={() => planificacionForm.handleEliminarPlanificacion(item.id)} /></td></tr>)}</tbody></table></div>
    {editing && <EditEntityModal title="Editar planificación DECE" onAccept={acceptEdit} onDiscard={() => setEditing(null)}>{fields(editing, setEditing)}</EditEntityModal>}
  </div>;
};

