import React, { useState } from 'react';
import { ActionIconButton, EditEntityModal, EditIcon, TrashIcon } from '../../../components/EditEntityModal';
import type { AdaptacionCurricular, CatalogItem, DiscapacidadGrado, DiscapacidadTipo } from '../../../types/entities/dece';

interface Props {
  adaptaciones: AdaptacionCurricular[];
  formOptions: { DISCAPACIDAD_TIPO_OPTIONS: DiscapacidadTipo[]; DISCAPACIDAD_GRADO_OPTIONS: DiscapacidadGrado[]; matriculas: CatalogItem[]; getMatriculaNombre: (id?: number | null, fallback?: string | null) => string };
  adaptacionForm: any;
}
const fieldStyle: React.CSSProperties = { width: '100%', height: '42px', padding: '0 12px', borderRadius: '8px', border: '1px solid var(--outline-variant)', background: 'var(--surface)', color: 'var(--on-surface)', fontSize: 'var(--font-body-sm)' };
const labelStyle: React.CSSProperties = { display: 'block', marginBottom: '6px', fontSize: 'var(--font-body-sm)', fontWeight: 600, color: 'var(--on-surface)' };
const catalogLabel = (item: CatalogItem) => [item.nombres, item.apellidos].filter(Boolean).join(' ').trim() || item.estudiante_nombre || item.nombre || item.codigo || `Matrícula ${item.id}`;
type EditState = { id: number; matricula: string; discapacidad_tipo: DiscapacidadTipo | ''; discapacidad_grado: DiscapacidadGrado | ''; necesidad_educativa: string };

export const TabAdaptacionCurricular: React.FC<Props> = ({ adaptaciones, adaptacionForm, formOptions }) => {
  const [editing, setEditing] = useState<EditState | null>(null);
  const openEdit = (item: AdaptacionCurricular) => setEditing({ id: item.id, matricula: String(item.matricula ?? ''), discapacidad_tipo: item.discapacidad_tipo, discapacidad_grado: item.discapacidad_grado, necesidad_educativa: item.necesidad_educativa ?? '' });
  const acceptEdit = async () => { if (!editing || !adaptacionForm.handleActualizarAdaptacion) return; if (await adaptacionForm.handleActualizarAdaptacion(editing.id, editing)) setEditing(null); };
  const fields = (state: EditState, setState: (value: EditState) => void) => <>
    <div><label style={labelStyle}>Matrícula</label><select value={state.matricula} onChange={(e) => setState({ ...state, matricula: e.target.value })} style={fieldStyle}><option value="">Seleccione matrícula...</option>{formOptions.matriculas.map((m) => <option key={m.id} value={m.id}>{catalogLabel(m)}</option>)}</select></div>
    <div><label style={labelStyle}>Tipo discapacidad</label><select value={state.discapacidad_tipo} onChange={(e) => setState({ ...state, discapacidad_tipo: e.target.value as DiscapacidadTipo })} style={fieldStyle}><option value="">Seleccione...</option>{formOptions.DISCAPACIDAD_TIPO_OPTIONS.map((t) => <option key={t} value={t}>{t}</option>)}</select></div>
    <div><label style={labelStyle}>Grado</label><select value={state.discapacidad_grado} onChange={(e) => setState({ ...state, discapacidad_grado: e.target.value as DiscapacidadGrado })} style={fieldStyle}><option value="">Seleccione...</option>{formOptions.DISCAPACIDAD_GRADO_OPTIONS.map((g) => <option key={g} value={g}>{g.replace('RANGO_', '').replace('_', '-')}</option>)}</select></div>
    <div><label style={labelStyle}>Necesidad educativa</label><input value={state.necesidad_educativa} onChange={(e) => setState({ ...state, necesidad_educativa: e.target.value })} placeholder="Ej. Adaptación en evaluación escrita" style={fieldStyle} /></div>
  </>;
  return <div style={{ display: 'flex', flexDirection: 'column', gap: '20px', width: '100%' }}>
    <form onSubmit={adaptacionForm.handleAgregarAdaptacion} style={{ background: 'var(--surface-container-lowest)', padding: '20px', borderRadius: '8px', border: '1px solid var(--outline-variant)', display: 'grid', gridTemplateColumns: 'repeat(4, minmax(0, 1fr)) auto', gap: '16px', width: '100%', boxSizing: 'border-box' }}>{fields({ id: 0, matricula: adaptacionForm.matriculaReferencia, discapacidad_tipo: adaptacionForm.discapacidadTipo, discapacidad_grado: adaptacionForm.discapacidadGrado, necesidad_educativa: adaptacionForm.necesidadEducativa }, (v) => { adaptacionForm.setMatriculaReferencia(v.matricula); adaptacionForm.setDiscapacidadTipo(v.discapacidad_tipo); adaptacionForm.setDiscapacidadGrado(v.discapacidad_grado); adaptacionForm.setNecesidadEducativa(v.necesidad_educativa); })}<div style={{ display: 'flex', gap: '8px', alignItems: 'flex-end' }}><button type="submit" style={{ background: 'var(--primary)', color: 'var(--on-primary)', border: 'none', padding: '0 18px', borderRadius: '8px', fontWeight: 600, cursor: 'pointer', height: '42px', whiteSpace: 'nowrap' }}>+ Agregar</button></div></form>
    <div style={{ background: 'var(--surface-container-lowest)', borderRadius: '8px', border: '1px solid var(--outline-variant)', overflow: 'hidden', width: '100%' }}><div style={{ padding: '14px 20px', borderBottom: '1px solid var(--outline-variant)' }}><h3 style={{ margin: 0, fontSize: 'var(--font-body-sm)', color: 'var(--primary)', fontWeight: '700' }}>Adaptaciones Curriculares</h3></div><table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left' }}><thead><tr style={{ background: 'var(--primary)', color: 'var(--on-primary)' }}><th style={{ padding: '12px 20px' }}>NRO</th><th style={{ padding: '12px 20px' }}>MATRÍCULA</th><th style={{ padding: '12px 20px' }}>TIPO</th><th style={{ padding: '12px 20px' }}>GRADO</th><th style={{ padding: '12px 20px' }}>NECESIDAD</th><th style={{ padding: '12px 20px', textAlign: 'center' }}>ACCIONES</th></tr></thead><tbody>{adaptaciones.length === 0 ? <tr><td colSpan={6} style={{ padding: '20px', textAlign: 'center', color: 'var(--on-surface-variant)' }}>No hay adaptaciones registradas.</td></tr> : adaptaciones.map((item, index) => <tr key={item.id} style={{ borderBottom: '1px solid var(--outline-variant)' }}><td style={{ padding: '12px 20px', color: 'var(--on-surface-variant)' }}>{(index + 1).toString().padStart(2, '0')}</td><td style={{ padding: '12px 20px', fontWeight: 600 }}>{formOptions.getMatriculaNombre(item.matricula, item.matricula_nombre || item.matricula_referencia)}</td><td style={{ padding: '12px 20px' }}>{item.discapacidad_tipo}</td><td style={{ padding: '12px 20px' }}>{item.discapacidad_grado}</td><td style={{ padding: '12px 20px', color: 'var(--on-surface-variant)' }}>{item.necesidad_educativa}</td><td style={{ padding: '12px 20px', textAlign: 'center' }}><ActionIconButton label="Editar" icon={<EditIcon />} onClick={() => openEdit(item)} style={{ marginRight: '8px' }} /><ActionIconButton label="Eliminar" icon={<TrashIcon />} tone="danger" onClick={() => adaptacionForm.handleEliminarAdaptacion(item.id)} /></td></tr>)}</tbody></table></div>
    {editing && <EditEntityModal title="Editar adaptación curricular" onAccept={acceptEdit} onDiscard={() => setEditing(null)}>{fields(editing, setEditing)}</EditEntityModal>}
  </div>;
};

