# Generated by Django 6.0.5 on 2026-05-24 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la Institución')),
                ('codigo_amie', models.CharField(max_length=50, unique=True, verbose_name='Código AMIE')),
                ('ruc', models.CharField(max_length=13, unique=True, verbose_name='RUC')),
                ('zona_coordinacion', models.CharField(choices=[('Z1', 'Coordinación Zonal 1'), ('Z2', 'Coordinación Zonal 2'), ('Z3', 'Coordinación Zonal 3'), ('Z4', 'Coordinación Zonal 4'), ('Z5', 'Coordinación Zonal 5'), ('Z6', 'Coordinación Zonal 6'), ('Z7', 'Coordinación Zonal 7'), ('Z8', 'Coordinación Zonal 8'), ('Z9', 'Coordinación Zonal 9')], max_length=2, verbose_name='Zona de Coordinación')),
                ('regimen', models.CharField(choices=[('CG', 'Costa-Galápagos'), ('SA', 'Sierra-Amazonía')], max_length=2, verbose_name='Régimen')),
                ('sostenimiento', models.CharField(choices=[('PAR', 'Particular'), ('FIS', 'Fiscomisional'), ('MUN', 'Municipal')], max_length=3, verbose_name='Sostenimiento')),
                ('modalidad', models.CharField(choices=[('PR', 'Presencial'), ('SP', 'Semipresencial'), ('AD', 'A distancia'), ('EL', 'En línea')], max_length=2, verbose_name='Modalidad')),
                ('jornada', models.CharField(choices=[('MAT', 'Matutino'), ('VES', 'Vespertino'), ('NOC', 'Nocturno')], max_length=3, verbose_name='Jornada')),
            ],
            options={
                'verbose_name': 'Institución',
                'verbose_name_plural': 'Instituciones',
                'db_table': 'tbl_instituciones',
            },
        ),
    ]
