# Generated by Django 6.0.5 on 2026-06-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0002_institucion_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='es_activo',
            field=models.BooleanField(default=True, verbose_name='¿Activo?'),
        ),
    ]
