# Generated by Django 6.0.5 on 2026-05-21 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actoresAcademicos', '0001_initial'),
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('periodoPedagogicoSemanaMinimo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EducacionNivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20)),
                ('periodoPedagogicoMinutos', models.IntegerField()),
                ('periodoPedagogicoSemanaMinimo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AnioLectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('esActivo', models.BooleanField(default=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anios_lectivos', to='configuracion.institucion')),
            ],
        ),
        migrations.CreateModel(
            name='AsignaturaOfertada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaturas_ofertadas', to='planificacion.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuantitativa', models.FloatField(blank=True, null=True)),
                ('cualitativa', models.CharField(blank=True, max_length=50, null=True)),
                ('asignaturaOfertada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='planificacion.asignaturaofertada')),
            ],
        ),
        migrations.CreateModel(
            name='EducacionSubNivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20)),
                ('periodoPedagogicoSemanaMinimo', models.IntegerField()),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subniveles', to='planificacion.educacionnivel')),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('subNivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grados', to='planificacion.educacionsubnivel')),
            ],
        ),
        migrations.AddField(
            model_name='asignatura',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='planificacion.grado'),
        ),
        migrations.CreateModel(
            name='GradoOfertado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grados_ofertados', to='planificacion.grado')),
            ],
        ),
        migrations.AddField(
            model_name='asignaturaofertada',
            name='gradoOfertado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas_ofertadas', to='planificacion.gradoofertado'),
        ),
        migrations.CreateModel(
            name='OfertaAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('anioLectivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ofertas', to='planificacion.aniolectivo')),
            ],
        ),
        migrations.AddField(
            model_name='gradoofertado',
            name='ofertaAcademica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grados_ofertados', to='planificacion.ofertaacademica'),
        ),
        migrations.CreateModel(
            name='Paralelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('cuposMaximo', models.IntegerField()),
                ('cuposOcupados', models.IntegerField(default=0)),
                ('docenteTutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paralelos_tutor', to='actoresAcademicos.docente')),
                ('gradoOfertado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paralelos', to='planificacion.gradoofertado')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('tipo', models.CharField(choices=[('Bimestre', 'Bimestre'), ('Trimestre', 'Trimestre'), ('Quimestre', 'Quimestre')], max_length=20)),
                ('anioLectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='planificacion.aniolectivo')),
            ],
        ),
        migrations.CreateModel(
            name='PlanEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('esActivo', models.BooleanField(default=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes_estudio', to='configuracion.institucion')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes_estudio', to='planificacion.educacionnivel')),
            ],
        ),
        migrations.AddField(
            model_name='grado',
            name='planEstudio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grados', to='planificacion.planestudio'),
        ),
    ]
