# Generated by Django 6.0.5 on 2026-05-24 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnioLectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('esActivo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Año Lectivo',
                'verbose_name_plural': 'Años Lectivos',
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('periodoPedagogicoSemanaMinimo', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
            },
        ),
        migrations.CreateModel(
            name='EducacionNivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('periodoPedagogicoMinutos', models.IntegerField()),
                ('periodoPedagogicoSemanaMinimo', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Nivel de Educación',
                'verbose_name_plural': 'Niveles de Educación',
            },
        ),
        migrations.CreateModel(
            name='EducacionSubNivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('periodoPedagogicoSemanaMinimo', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Subnivel de Educación',
                'verbose_name_plural': 'Subniveles de Educación',
            },
        ),
        migrations.CreateModel(
            name='PlanEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('esActivo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plan de Estudio',
                'verbose_name_plural': 'Planes de Estudio',
            },
        ),
        migrations.CreateModel(
            name='AsignaturaOfertada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas_ofertadas', to='planificacion.asignatura')),
            ],
            options={
                'verbose_name': 'Asignatura Ofertada',
                'verbose_name_plural': 'Asignaturas Ofertadas',
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuantitativa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cualitativa', models.CharField(max_length=50)),
                ('asignaturaOfertada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='planificacion.asignaturaofertada')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('educacionNivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grados', to='planificacion.educacionnivel')),
                ('educacionSubNivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grados', to='planificacion.educacionsubnivel')),
                ('planEstudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grados', to='planificacion.planestudio')),
            ],
            options={
                'verbose_name': 'Grado',
                'verbose_name_plural': 'Grados',
            },
        ),
        migrations.AddField(
            model_name='asignatura',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='planificacion.grado'),
        ),
        migrations.CreateModel(
            name='GradoOfertado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grados_ofertados', to='planificacion.grado')),
            ],
            options={
                'verbose_name': 'Grado Ofertado',
                'verbose_name_plural': 'Grados Ofertados',
            },
        ),
        migrations.AddField(
            model_name='asignaturaofertada',
            name='gradoOfertado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas_ofertadas', to='planificacion.gradoofertado'),
        ),
        migrations.CreateModel(
            name='OfertaAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('anioLectivo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oferta_academica', to='planificacion.aniolectivo')),
            ],
            options={
                'verbose_name': 'Oferta Académica',
                'verbose_name_plural': 'Ofertas Académicas',
            },
        ),
        migrations.AddField(
            model_name='gradoofertado',
            name='ofertaAcademica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grados_ofertados', to='planificacion.ofertaacademica'),
        ),
        migrations.CreateModel(
            name='Paralelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('cuposMaximo', models.IntegerField()),
                ('cuposOcupados', models.IntegerField(default=0)),
                ('gradoOfertado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paralelos', to='planificacion.gradoofertado')),
            ],
            options={
                'verbose_name': 'Paralelo',
                'verbose_name_plural': 'Paralelos',
            },
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('periodoTipo', models.CharField(choices=[('BIMESTRE', 'Bimestre'), ('TRIMESTRE', 'Trimestre'), ('QUIMESTRE', 'Quimestre')], max_length=20)),
                ('anioLectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos_academicos', to='planificacion.aniolectivo')),
            ],
            options={
                'verbose_name': 'Período Académico',
                'verbose_name_plural': 'Períodos Académicos',
            },
        ),
    ]
