# Generated by Django 5.2.14 on 2026-06-20 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matricula', '0004_matricula_exceder_cupo_autorizado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(blank=True, default='', max_length=255)),
                ('descripcion', models.CharField(blank=True, default='', max_length=500)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_CURSO', 'En curso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PROGRAMADO', max_length=20)),
                ('distributivo_asignatura_id', models.IntegerField()),
                ('horario_id', models.IntegerField(blank=True, null=True)),
                ('distributivo_evaluacion_id', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
                'db_table': 'clase',
                'ordering': ['-fecha', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(blank=True, default='', max_length=500)),
                ('notificar', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('ASISTENCIA', 'Asistencia'), ('INASISTENCIA', 'Inasistencia'), ('JUSTIFICADO', 'Justificado'), ('ATRASADO', 'Atrasado')], default='ASISTENCIA', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('matricula', models.ForeignKey(db_column='matricula_id', on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='matricula.matricula')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_registradas', to=settings.AUTH_USER_MODEL)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='asistencia.clase')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'db_table': 'asistencia',
                'unique_together': {('clase', 'matricula')},
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=150)),
                ('detalle', models.TextField(blank=True, default='')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='incidencias_asistencia/%Y/%m/')),
                ('notificar', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('COMPORTAMIENTO', 'Comportamiento'), ('ACADEMICO', 'Académico'), ('ASISTENCIAL', 'Asistencial')], default='ASISTENCIAL', max_length=20)),
                ('estado', models.CharField(default='REGISTRADA', max_length=20)),
                ('incidencia_calificacion_id', models.IntegerField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('asistencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='asistencia.asistencia')),
                ('matricula', models.ForeignKey(blank=True, db_column='matricula_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidencias_asistencia', to='matricula.matricula')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'db_table': 'incidencia_asistencia',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Justificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('motivo', models.TextField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='justificaciones/%Y/%m/')),
                ('observacion_secretaria', models.TextField(blank=True, default='')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificaciones', to='asistencia.asistencia')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificaciones_resueltas', to=settings.AUTH_USER_MODEL)),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificaciones_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Justificación',
                'verbose_name_plural': 'Justificaciones',
                'db_table': 'justificacion',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
