# Generated by Django 6.0.5 on 2026-05-19 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('tipo_identificacion', models.CharField(choices=[('CEDULA', 'Cédula'), ('PASAPORTE', 'Pasaporte')], max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('correo_personal', models.EmailField(max_length=254, unique=True)),
                ('rol_administrado', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Autoridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('tipo_identificacion', models.CharField(choices=[('CEDULA', 'Cédula'), ('PASAPORTE', 'Pasaporte')], max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('correo_personal', models.EmailField(max_length=254, unique=True)),
                ('correo_institucional', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('es_activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('tipo_identificacion', models.CharField(choices=[('CEDULA', 'Cédula'), ('PASAPORTE', 'Pasaporte')], max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('correo_personal', models.EmailField(max_length=254, unique=True)),
                ('correo_institucional', models.EmailField(max_length=254, unique=True)),
                ('especialidad', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('tipo_identificacion', models.CharField(choices=[('CEDULA', 'Cédula'), ('PASAPORTE', 'Pasaporte')], max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('correo_personal', models.EmailField(max_length=254, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='estudiantes/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('tipo_identificacion', models.CharField(choices=[('CEDULA', 'Cédula'), ('PASAPORTE', 'Pasaporte')], max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('correo_personal', models.EmailField(max_length=254, unique=True)),
                ('correo_institucional', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('AUTORIDAD', 'Autoridad Académica'), ('DOCENTE', 'Docente'), ('SECRETARIA', 'Secretaria'), ('ESTUDIANTE', 'Estudiante'), ('DECE', 'DECE')], max_length=30)),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actoresAcademicos.permiso')),
            ],
        ),
    ]
