# Generated by Django 6.0.5 on 2026-05-20 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actoresAcademicos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='correo',
            new_name='correo_institucional',
        ),
        migrations.RenameField(
            model_name='cuenta',
            old_name='usuario',
            new_name='nombre_usuario',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='es_activo',
        ),
        migrations.AddField(
            model_name='administrador',
            name='cuenta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_administrador', to='actoresAcademicos.cuenta'),
        ),
        migrations.AddField(
            model_name='autoridad',
            name='cuenta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_autoridad', to='actoresAcademicos.cuenta'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='rol',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('AUTORIDAD', 'Autoridad Académica'), ('DOCENTE', 'Docente'), ('DOCENTE_TUTOR', 'Docente Tutor'), ('SECRETARIA', 'Secretaria'), ('ESTUDIANTE', 'Estudiante'), ('DECE', 'DECE')], default='ESTUDIANTE', max_length=30),
        ),
        migrations.AddField(
            model_name='docente',
            name='cuenta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_docente', to='actoresAcademicos.cuenta'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='cuenta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_estudiante', to='actoresAcademicos.cuenta'),
        ),
        migrations.AddField(
            model_name='secretaria',
            name='cuenta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_secretaria', to='actoresAcademicos.cuenta'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='rol_administrado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='autoridad',
            name='correo_institucional',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='rolpermiso',
            name='rol',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('AUTORIDAD', 'Autoridad Académica'), ('DOCENTE', 'Docente'), ('DOCENTE_TUTOR', 'Docente Tutor'), ('SECRETARIA', 'Secretaria'), ('ESTUDIANTE', 'Estudiante'), ('DECE', 'DECE')], max_length=30),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='correo_institucional',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Dece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('tipo_identificacion', models.CharField(choices=[('CEDULA', 'Cédula'), ('PASAPORTE', 'Pasaporte')], max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('correo_personal', models.EmailField(max_length=254, unique=True)),
                ('cuenta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_dece', to='actoresAcademicos.cuenta')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
