# Generated by Django 6.0.5 on 2026-05-20 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actoresAcademicos', '0002_rename_correo_cuenta_correo_institucional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='es_activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='cuenta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_estudiante', to='actoresAcademicos.cuenta'),
        ),
    ]
