# Generated by Django 6.0.5 on 2026-05-25 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actoresAcademicos', '0004_universidad_docente_tipo_contrato_and_more'),
        ('ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='direccion_domicilio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_direccion', related_query_name='%(app_label)s_%(class)s_direcciones', to='ubicacion.direccion', verbose_name='Dirección Domiciliaria'),
        ),
        migrations.AddField(
            model_name='autoridad',
            name='direccion_domicilio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_direccion', related_query_name='%(app_label)s_%(class)s_direcciones', to='ubicacion.direccion', verbose_name='Dirección Domiciliaria'),
        ),
        migrations.AddField(
            model_name='dece',
            name='direccion_domicilio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_direccion', related_query_name='%(app_label)s_%(class)s_direcciones', to='ubicacion.direccion', verbose_name='Dirección Domiciliaria'),
        ),
        migrations.AddField(
            model_name='docente',
            name='direccion_domicilio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_direccion', related_query_name='%(app_label)s_%(class)s_direcciones', to='ubicacion.direccion', verbose_name='Dirección Domiciliaria'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='direccion_domicilio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_direccion', related_query_name='%(app_label)s_%(class)s_direcciones', to='ubicacion.direccion', verbose_name='Dirección Domiciliaria'),
        ),
        migrations.AddField(
            model_name='secretaria',
            name='direccion_domicilio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_direccion', related_query_name='%(app_label)s_%(class)s_direcciones', to='ubicacion.direccion', verbose_name='Dirección Domiciliaria'),
        ),
    ]
