# Generated by Django 6.0.5 on 2026-05-27 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actoresAcademicos', '0005_administrador_direccion_domicilio_and_more'),
        ('ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='universidad',
            name='direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='universidades', to='ubicacion.direccion', verbose_name='Dirección de la Universidad'),
        ),
    ]
