# Generated by Django 6.0.5 on 2026-05-22 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Cantón')),
            ],
            options={
                'verbose_name': 'Cantón',
                'verbose_name_plural': 'Cantones',
                'db_table': 'tbl_cantones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del País')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'db_table': 'tbl_paises',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Parroquia')),
                ('canton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parroquias', to='ubicacion.canton', verbose_name='Cantón Asociado')),
            ],
            options={
                'verbose_name': 'Parroquia',
                'verbose_name_plural': 'Parroquias',
                'db_table': 'tbl_parroquias',
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'canton')},
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle_principal', models.CharField(max_length=150, verbose_name='Calle Principal')),
                ('calle_secundaria', models.CharField(max_length=150, verbose_name='Calle Secundaria')),
                ('numero_casa', models.CharField(max_length=20, verbose_name='Número de Casa/Departamento')),
                ('referencia', models.TextField(verbose_name='Referencia Domiciliaria')),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direcciones', to='ubicacion.parroquia', verbose_name='Parroquia Domiciliaria')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
                'db_table': 'tbl_direcciones',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Provincia')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincias', to='ubicacion.pais', verbose_name='País Asociado')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'db_table': 'tbl_provincias',
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'pais')},
            },
        ),
        migrations.AddField(
            model_name='canton',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cantones', to='ubicacion.provincia', verbose_name='Provincia Asociada'),
        ),
        migrations.AlterUniqueTogether(
            name='canton',
            unique_together={('nombre', 'provincia')},
        ),
    ]
