# Generated by Django 6.0.5 on 2026-06-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canton',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
        migrations.AddField(
            model_name='pais',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='parroquia',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='parroquia',
            name='tipo_parroquia',
            field=models.CharField(choices=[('URBANA', 'Urbana'), ('RURAL', 'Rural')], default='URBANA', max_length=10, verbose_name='Tipo de Parroquia'),
        ),
        migrations.AddField(
            model_name='provincia',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
