# Generated by Django 6.0.5 on 2026-05-25 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0001_initial'),
        ('ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='direccion',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='institucion', to='ubicacion.direccion', verbose_name='Dirección de la Sede'),
            preserve_default=False,
        ),
    ]
