# Generated by Django 6.0.5 on 2026-06-14 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institucion', '0002_institucion_direccion'),
        ('ubicacion', '0002_canton_is_active_direccion_is_active_pais_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=50, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('correo_institucional', models.EmailField(max_length=254, unique=True)),
                ('rol', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('AUTORIDAD', 'Autoridad Académica'), ('DOCENTE', 'Docente'), ('DOCENTE_TUTOR', 'Docente Tutor'), ('SECRETARIA', 'Secretaria'), ('ESTUDIANTE', 'Estudiante'), ('DECE', 'DECE')], default='ESTUDIANTE', max_length=30)),
                ('es_activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Autoridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('tipo_identificacion', models.CharField(choices=[('CEDULA', 'Cédula'), ('PASAPORTE', 'Pasaporte')], max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('correo_personal', models.EmailField(max_length=254, unique=True)),
                ('correo_institucional', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('direccion_domicilio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_direccion', related_query_name='%(app_label)s_%(class)s_direcciones', to='ubicacion.direccion', verbose_name='Dirección Domiciliaria')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autoridades', to='institucion.institucion')),
                ('cuenta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_autoridad', to='actoresAcademicos.cuenta')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('tipo_identificacion', models.CharField(choices=[('CEDULA', 'Cédula'), ('PASAPORTE', 'Pasaporte')], max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('correo_personal', models.EmailField(max_length=254, unique=True)),
                ('rol_administrado', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion_domicilio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_direccion', related_query_name='%(app_label)s_%(class)s_direcciones', to='ubicacion.direccion', verbose_name='Dirección Domiciliaria')),
                ('cuenta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_administrador', to='actoresAcademicos.cuenta')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('tipo_identificacion', models.CharField(choices=[('CEDULA', 'Cédula'), ('PASAPORTE', 'Pasaporte')], max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('correo_personal', models.EmailField(max_length=254, unique=True)),
                ('cuenta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_dece', to='actoresAcademicos.cuenta')),
                ('direccion_domicilio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_direccion', related_query_name='%(app_label)s_%(class)s_direcciones', to='ubicacion.direccion', verbose_name='Dirección Domiciliaria')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deces', to='institucion.institucion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('tipo_identificacion', models.CharField(choices=[('CEDULA', 'Cédula'), ('PASAPORTE', 'Pasaporte')], max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('correo_personal', models.EmailField(max_length=254, unique=True)),
                ('correo_institucional', models.EmailField(max_length=254, unique=True)),
                ('especialidad', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField()),
                ('tipo_contrato', models.CharField(choices=[('TIT', 'Titular'), ('INV', 'Invitado'), ('OCA', 'Ocasional'), ('HON', 'Honorarios'), ('EME', 'Eméritos')], max_length=3, verbose_name='Tipo de Contrato')),
                ('tipo_dedicacion', models.CharField(choices=[('TC', 'Tiempo completo'), ('TP', 'Tiempo parcial'), ('MT', 'Medio tiempo')], max_length=2, verbose_name='Tipo de Dedicación')),
                ('cuenta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_docente', to='actoresAcademicos.cuenta')),
                ('direccion_domicilio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_direccion', related_query_name='%(app_label)s_%(class)s_direcciones', to='ubicacion.direccion', verbose_name='Dirección Domiciliaria')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('tipo_identificacion', models.CharField(choices=[('CEDULA', 'Cédula'), ('PASAPORTE', 'Pasaporte')], max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('correo_personal', models.EmailField(max_length=254, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='estudiantes/')),
                ('cuenta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_estudiante', to='actoresAcademicos.cuenta')),
                ('direccion_domicilio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_direccion', related_query_name='%(app_label)s_%(class)s_direcciones', to='ubicacion.direccion', verbose_name='Dirección Domiciliaria')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('AUTORIDAD', 'Autoridad Académica'), ('DOCENTE', 'Docente'), ('DOCENTE_TUTOR', 'Docente Tutor'), ('SECRETARIA', 'Secretaria'), ('ESTUDIANTE', 'Estudiante'), ('DECE', 'DECE')], max_length=30)),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actoresAcademicos.permiso')),
            ],
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('tipo_identificacion', models.CharField(choices=[('CEDULA', 'Cédula'), ('PASAPORTE', 'Pasaporte')], max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('correo_personal', models.EmailField(max_length=254, unique=True)),
                ('correo_institucional', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('cuenta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_secretaria', to='actoresAcademicos.cuenta')),
                ('direccion_domicilio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_direccion', related_query_name='%(app_label)s_%(class)s_direcciones', to='ubicacion.direccion', verbose_name='Dirección Domiciliaria')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secretarias', to='institucion.institucion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la Universidad')),
                ('direccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='universidades', to='ubicacion.direccion', verbose_name='Dirección de la Universidad')),
            ],
            options={
                'verbose_name': 'Universidad',
                'verbose_name_plural': 'Universidades',
                'db_table': 'tbl_universidades',
            },
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título Obtenido')),
                ('fecha_senescyt', models.DateField(verbose_name='Fecha de Registro Senescyt')),
                ('registro_senescyt', models.CharField(max_length=100, unique=True, verbose_name='Número de Registro Senescyt')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titulos', to='actoresAcademicos.docente', verbose_name='Docente')),
                ('universidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='titulos_otorgados', to='actoresAcademicos.universidad', verbose_name='Universidad')),
            ],
            options={
                'verbose_name': 'Título del Docente',
                'verbose_name_plural': 'Títulos del Docente',
                'db_table': 'tbl_titulos_docentes',
            },
        ),
    ]
