# Generated by Django 6.0.5 on 2026-06-15 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actoresAcademicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dece',
            name='correo_institucional',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
