# Generated by Django 6.0.5 on 2026-06-20 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actoresAcademicos', '0002_dece_correo_institucional'),
        ('institucion', '0002_institucion_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='institucion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='docentes', to='institucion.institucion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='correo_institucional',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='institucion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes', to='institucion.institucion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='docente',
            name='correo_institucional',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
