# Generated by Django 6.0.5 on 2026-05-25 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actoresAcademicos', '0003_cuenta_es_activo_alter_estudiante_cuenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la Universidad')),
            ],
            options={
                'verbose_name': 'Universidad',
                'verbose_name_plural': 'Universidades',
                'db_table': 'tbl_universidades',
            },
        ),
        migrations.AddField(
            model_name='docente',
            name='tipo_contrato',
            field=models.CharField(choices=[('TIT', 'Titular'), ('INV', 'Invitado'), ('OCA', 'Ocasional'), ('HON', 'Honorarios'), ('EME', 'Eméritos')], default='TIT', max_length=3, verbose_name='Tipo de Contrato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docente',
            name='tipo_dedicacion',
            field=models.CharField(choices=[('TC', 'Tiempo completo'), ('TP', 'Tiempo parcial'), ('MT', 'Medio tiempo')], default='2026-01-01', max_length=2, verbose_name='Tipo de Dedicación'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título Obtenido')),
                ('fecha_senescyt', models.DateField(verbose_name='Fecha de Registro Senescyt')),
                ('registro_senescyt', models.CharField(max_length=100, unique=True, verbose_name='Número de Registro Senescyt')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titulos', to='actoresAcademicos.docente', verbose_name='Docente')),
                ('universidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='titulos_otorgados', to='actoresAcademicos.universidad', verbose_name='Universidad')),
            ],
            options={
                'verbose_name': 'Título del Docente',
                'verbose_name_plural': 'Títulos del Docente',
                'db_table': 'tbl_titulos_docentes',
            },
        ),
    ]
