# Generated by Django 6.0.5 on 2026-06-21 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actoresAcademicos', '0003_docente_institucion_estudiante_correo_institucional_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoridad',
            name='correo_institucional',
        ),
        migrations.RemoveField(
            model_name='dece',
            name='correo_institucional',
        ),
        migrations.RemoveField(
            model_name='secretaria',
            name='correo_institucional',
        ),
    ]
