# Generated by Django 6.0.5 on 2026-06-21 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actoresAcademicos', '0004_remove_autoridad_correo_institucional_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='correo_institucional',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='correo_institucional',
        ),
    ]
