# Generated by Django 6.0.5 on 2026-06-22 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actoresAcademicos', '0005_remove_docente_correo_institucional_and_more'),
        ('ubicacion', '0002_canton_is_active_direccion_is_active_pais_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='direccion_domicilio',
        ),
        migrations.AlterField(
            model_name='autoridad',
            name='direccion_domicilio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autoridad_direccion', to='ubicacion.direccion', verbose_name='Dirección Domiciliaria'),
        ),
        migrations.AlterField(
            model_name='dece',
            name='direccion_domicilio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dece_direccion', to='ubicacion.direccion', verbose_name='Dirección Domiciliaria'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='direccion_domicilio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docente_direccion', to='ubicacion.direccion', verbose_name='Dirección Domiciliaria'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='direccion_domicilio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiante_direccion', to='ubicacion.direccion', verbose_name='Dirección Domiciliaria'),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='direccion_domicilio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretaria_direccion', to='ubicacion.direccion', verbose_name='Dirección Domiciliaria'),
        ),
    ]
