# Generated by Django 6.0.5 on 2026-05-24 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=200)),
                ('detalle', models.TextField()),
                ('fechaReunion', models.DateTimeField(blank=True, null=True)),
                ('emailEnviar', models.BooleanField(default=False)),
                ('notificacionTipo', models.CharField(choices=[('INFORMATIVA', 'Informativa'), ('REUNION', 'Reunión'), ('INCIDENCIA', 'Incidencia')], max_length=20)),
                ('emailEstado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado')], default='PENDIENTE', max_length=20)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='Destinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmacion', models.BooleanField(default=False)),
                ('visto', models.BooleanField(default=False)),
                ('vistoFecha', models.DateTimeField(blank=True, null=True)),
                ('emailFechaEnvio', models.DateTimeField(blank=True, null=True)),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='comunicacion.notificacion')),
            ],
            options={
                'verbose_name': 'Destinatario',
                'verbose_name_plural': 'Destinatarios',
            },
        ),
    ]
