# Generated by Django 5.2.14 on 2026-05-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('nota_minima', models.IntegerField()),
                ('nota_maxima', models.IntegerField()),
                ('tipo_calculo', models.CharField(choices=[('SIMPLE', 'Simple'), ('PONDERADO', 'Ponderado'), ('SUPLETORIO', 'Supletorio')], default='SIMPLE', max_length=20)),
            ],
        ),
    ]
