# Generated by Django 5.2.14 on 2026-05-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionRubrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('institucion_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('esActivo', models.BooleanField(default=True)),
                ('evaluacion_tipo', models.CharField(choices=[('CUALITATIVA', 'Cualitativa'), ('CUANTITATIVA', 'Cuantitativa')], default='CUALITATIVA', max_length=20)),
            ],
        ),
    ]
