# Generated by Django 5.2.14 on 2026-05-23 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0002_evaluacionrubrica'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionEquivalencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('evaluacion_rubrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equivalencias', to='calificaciones.evaluacionrubrica')),
            ],
        ),
    ]
