# Generated by Django 5.2.14 on 2026-05-23 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0003_evaluacionequivalencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionCriterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuantitativaMinima', models.IntegerField()),
                ('cuantitativaMaxima', models.IntegerField()),
                ('cualitativa', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('evaluacion_equivalencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='calificaciones.evaluacionequivalencia')),
                ('evaluacion_rubrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='calificaciones.evaluacionrubrica')),
            ],
        ),
    ]
