# Generated by Django 5.2.14 on 2026-05-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0004_evaluacioncriterio'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('institucion_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('anio_lectivo_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('grado_id', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
