# Generated by Django 5.2.14 on 2026-05-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0005_evaluacionlibro'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacioncategoria',
            name='periodoAcademico_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
