# Generated by Django 5.2.14 on 2026-05-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0007_evaluacioncategoria_padre'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionrubrica',
            name='asignatura_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluacionrubrica',
            name='grado_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
