# Generated by Django 5.2.15 on 2026-06-24 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0008_evaluacionrubrica_asignatura_id_and_more'),
        ('distributivos', '0009_distributivoasignatura_paralelo_and_more'),
        ('matricula', '0010_matricula_asp_apellidos_and_more'),
        ('planificacion', '0008_aniolectivo_institucion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignaturaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('distributivo_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='distributivos.distributivoasignatura')),
                ('periodo_academico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to='planificacion.periodoacademico')),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('asignatura_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='calificaciones.asignaturaevaluacion')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='matricula.matricula')),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_anterior', models.DecimalField(decimal_places=2, max_digits=6)),
                ('valor_nuevo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='calificaciones.calificacion')),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionMejora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('REFUERZO', 'Refuerzo'), ('PEDAGOGICO', 'Pedagógico'), ('MEJORA', 'Mejora')], default='MEJORA', max_length=20)),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mejoras', to='calificaciones.calificacion')),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=150)),
                ('detalle', models.TextField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='incidencias/')),
                ('notificar', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('COMPORTAMIENTO', 'Comportamiento'), ('ACADEMICO', 'Académico'), ('ASISTENCIAL', 'Asistencial')], default='COMPORTAMIENTO', max_length=20)),
                ('calificaciones', models.ManyToManyField(blank=True, related_name='incidencias', to='calificaciones.calificacion')),
            ],
        ),
        migrations.CreateModel(
            name='Promedio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_calculo', models.DateTimeField(blank=True, null=True)),
                ('distributivo_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promedios', to='distributivos.distributivoasignatura')),
                ('evaluacion_rubrica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promedios', to='calificaciones.evaluacionrubrica')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promedios', to='matricula.matricula')),
                ('periodo_academico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promedios', to='planificacion.periodoacademico')),
            ],
        ),
        migrations.CreateModel(
            name='PromedioCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('observacion', models.TextField(blank=True)),
                ('evaluacion_categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promedios_categoria', to='calificaciones.evaluacioncategoria')),
                ('promedio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promedios_categoria', to='calificaciones.promedio')),
                ('promedio_categoria_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='calificaciones.promediocategoria')),
            ],
        ),
        migrations.AddField(
            model_name='calificacion',
            name='promedio_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='calificaciones.promediocategoria'),
        ),
        migrations.AddConstraint(
            model_name='promedio',
            constraint=models.UniqueConstraint(fields=('matricula', 'distributivo_asignatura', 'periodo_academico'), name='unique_promedio_por_matricula_asignatura_periodo'),
        ),
        migrations.AddConstraint(
            model_name='calificacion',
            constraint=models.UniqueConstraint(fields=('asignatura_evaluacion', 'matricula'), name='unique_calificacion_por_evaluacion_matricula'),
        ),
    ]
