# Generated by Django 5.2.13 on 2026-05-24 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptacionCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula_referencia', models.CharField(blank=True, help_text='TODO: replace with FK to Matricula when module exists.', max_length=150, null=True, unique=True)),
                ('discapacidad_tipo', models.CharField(choices=[('VISUAL', 'Visual'), ('AUDITIVA', 'Auditiva'), ('FISICA', 'Fisica'), ('INTELECTUAL', 'Intelectual'), ('LENGUAJE', 'Lenguaje'), ('PSICOSOCIAL', 'Psicosocial'), ('MULTIPLE', 'Multiple')], max_length=20)),
                ('discapacidad_grado', models.CharField(choices=[('RANGO_0_4', '0-4'), ('RANGO_5_24', '5-24'), ('RANGO_25_49', '25-49'), ('RANGO_50_74', '50-74'), ('RANGO_75_95', '75-95'), ('RANGO_96_100', '96-100')], max_length=20)),
                ('necesidad_educativa', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Adaptacion Curricular',
                'verbose_name_plural': 'Adaptaciones Curriculares',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdaptacionCurricularEvidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='dece/evidencias/')),
                ('descripcion', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adaptacion_curricular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='dece.adaptacioncurricular')),
            ],
            options={
                'verbose_name': 'Adaptacion Curricular Evidencia',
                'verbose_name_plural': 'Adaptaciones Curriculares Evidencias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdaptacionCurricularPlanificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributivo_asignatura_referencia', models.CharField(blank=True, help_text='TODO: replace with FK to DistributivoAsignatura when module exists.', max_length=150, null=True)),
                ('archivo', models.FileField(upload_to='dece/planificaciones/')),
                ('comentario', models.TextField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADO', 'Enviado'), ('NO_APROBADO', 'No aprobado'), ('APROBADO', 'Aprobado')], default='BORRADOR', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adaptacion_curricular', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planificacion', to='dece.adaptacioncurricular')),
            ],
            options={
                'verbose_name': 'Adaptacion Curricular Planificacion',
                'verbose_name_plural': 'Adaptaciones Curriculares Planificaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
