# Generated by Django 6.0.5 on 2026-05-24 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0002_educacionnivel_nivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educacionnivel',
            name='nivel',
        ),
        migrations.AddField(
            model_name='educacionsubnivel',
            name='nivel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subniveles', to='planificacion.educacionnivel'),
            preserve_default=False,
        ),
    ]
