# Generated by Django 6.0.5 on 2026-06-20 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0002_institucion_direccion'),
        ('planificacion', '0003_remove_educacionnivel_nivel_educacionsubnivel_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aniolectivo',
            name='institucion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='anios_lectivos', to='institucion.institucion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planestudio',
            name='institucion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='planes_estudio', to='institucion.institucion'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Calificacion',
        ),
    ]
