# Generated by Django 5.2.14 on 2026-06-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0004_estado_aniolectivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='planestudio',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='planestudio',
            name='duracionAnios',
            field=models.IntegerField(default=1),
        ),
    ]
