# Generated by Django 5.2.14 on 2026-06-21 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0002_institucion_direccion'),
        ('planificacion', '0005_planestudio_descripcion_planestudio_duracionanios'),
    ]

    operations = [
        migrations.AddField(
            model_name='grado',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grados', to='institucion.institucion'),
        ),
        migrations.AddField(
            model_name='planestudio',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planes_estudio', to='institucion.institucion'),
        ),
    ]
