# Generated by Django 5.2.14 on 2026-06-21 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actoresAcademicos', '0003_docente_institucion_estudiante_correo_institucional_and_more'),
        ('planificacion', '0006_grado_institucion_planestudio_institucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='paralelo',
            name='docenteTutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paralelos_tutor', to='actoresAcademicos.docente'),
        ),
        migrations.AddField(
            model_name='paralelo',
            name='jornada',
            field=models.CharField(choices=[('MATUTINA', 'Matutina'), ('VESPERTINA', 'Vespertina'), ('NOCTURNA', 'Nocturna')], default='MATUTINA', max_length=20),
        ),
    ]
