# Generated by Django 6.0.5 on 2026-06-23 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0003_institucion_es_activo'),
        ('planificacion', '0007_paralelo_docentetutor_paralelo_jornada'),
    ]

    operations = [
        migrations.AddField(
            model_name='aniolectivo',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anios_lectivos', to='institucion.institucion'),
        ),
    ]
