# Generated by Django 6.0.6 on 2026-06-25 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0009_seed_grados_asignaturas'),
        ('planificacion', '0011_paralelo_docentetutor_remove_asignaturaofertada_docentetutor'),
    ]

    operations = [
    ]
