# Generated by Django 6.0.5 on 2026-08-21 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0011_eliminar_tablas_niveles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grado',
            name='anioGrado',
            field=models.IntegerField(help_text='Número de año dentro del subnivel (ej: 1°, 2°, 3°)'),
        ),
        migrations.AlterField(
            model_name='grado',
            name='nivel',
            field=models.CharField(choices=[('Educación Inicial', 'INICIAL'), ('Educación General Básica', 'EGB'), ('Bachillerato', 'BACHILLERATO')], help_text='Nivel educativo del grado', max_length=30),
        ),
        migrations.AlterField(
            model_name='grado',
            name='subnivel',
            field=models.CharField(choices=[('Inicial 1 (No Escolarizado)', 'INICIAL_1'), ('Inicial 2 (Escolarizado)', 'INICIAL_2'), ('Preparatoria (1° EGB)', 'PREPARATORIA'), ('Básica Elemental (2°-4° EGB)', 'BASICA_ELEMENTAL'), ('Básica Media (5°-7° EGB)', 'BASICA_MEDIA'), ('Básica Superior (8°-10° EGB)', 'BASICA_SUPERIOR'), ('Bachillerato en Ciencias', 'BACHILLERATO_CIENCIAS'), ('Bachillerato Técnico', 'BACHILLERATO_TECNICO')], help_text='Subnivel educativo del grado', max_length=50),
        ),
    ]
