# Generated by Django 6.0.5 on 2026-08-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0012_alter_grado_aniogrado_alter_grado_nivel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradoofertado',
            name='esActivo',
            field=models.BooleanField(default=True),
        ),
    ]
