# Generated by Django 6.0.5 on 2026-08-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0013_gradoofertado_esactivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignaturaofertada',
            name='esActivo',
            field=models.BooleanField(default=True),
        ),
    ]
