# Generated by Django 5.2.14 on 2026-05-19 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatriculaPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('Ordinaria', 'Ordinaria'), ('Extraordinaria', 'Extraordinaria'), ('Especial', 'Especial')], default='Ordinaria', max_length=20)),
                ('institucion_id', models.IntegerField(blank=True, null=True)),
                ('educacion_nivel_id', models.IntegerField(blank=True, null=True)),
                ('anio_lectivo_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Período de Matrícula',
                'verbose_name_plural': 'Períodos de Matrícula',
                'db_table': 'matricula_periodo',
            },
        ),
        migrations.CreateModel(
            name='MatriculaRequisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('tipo', models.CharField(choices=[('Informativo', 'Informativo'), ('Evidencia', 'Evidencia')], default='Informativo', max_length=20)),
            ],
            options={
                'verbose_name': 'Requisito de Matrícula',
                'verbose_name_plural': 'Requisitos de Matrícula',
                'db_table': 'matricula_requisito',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('promedio_anual', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Prematricula', 'Prematrícula'), ('Solicitud', 'Solicitud'), ('Legalizada', 'Legalizada'), ('Rechazada', 'Rechazada'), ('Anulada', 'Anulada')], default='Prematricula', max_length=20)),
                ('representante_id', models.IntegerField(blank=True, null=True)),
                ('secretaria_id', models.IntegerField(blank=True, null=True)),
                ('estudiante_id', models.IntegerField(blank=True, null=True)),
                ('paralelo_id', models.IntegerField(blank=True, null=True)),
                ('matricula_periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='matricula.matriculaperiodo')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'db_table': 'matricula',
            },
        ),
        migrations.AddField(
            model_name='matriculaperiodo',
            name='requisitos',
            field=models.ManyToManyField(blank=True, related_name='periodos', to='matricula.matricularequisito'),
        ),
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='matricula/requisitos/')),
                ('observacion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Validado', 'Validado'), ('No validado', 'No validado')], default='Pendiente', max_length=20)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='matricula.matricula')),
                ('matricula_requisito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitos_entregados', to='matricula.matricularequisito')),
            ],
            options={
                'verbose_name': 'Requisito',
                'verbose_name_plural': 'Requisitos',
                'db_table': 'requisito',
            },
        ),
        migrations.CreateModel(
            name='Retiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.TextField()),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retiros', to='matricula.matricula')),
            ],
            options={
                'verbose_name': 'Retiro',
                'verbose_name_plural': 'Retiros',
                'db_table': 'retiro',
            },
        ),
    ]
