# Generated by Django 5.2.14 on 2026-05-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matricula',
            options={'verbose_name': 'Matricula', 'verbose_name_plural': 'Matriculas'},
        ),
        migrations.AlterModelOptions(
            name='matriculaperiodo',
            options={'verbose_name': 'Periodo de Matricula', 'verbose_name_plural': 'Periodos de Matricula'},
        ),
        migrations.AlterModelOptions(
            name='matricularequisito',
            options={'verbose_name': 'Requisito de Matricula', 'verbose_name_plural': 'Requisitos de Matricula'},
        ),
        migrations.AlterModelOptions(
            name='requisito',
            options={'verbose_name': 'Requisito Entregado', 'verbose_name_plural': 'Requisitos Entregados'},
        ),
        migrations.AlterField(
            model_name='matricula',
            name='estado',
            field=models.CharField(choices=[('Prematricula', 'Prematricula'), ('Solicitud', 'Solicitud'), ('Legalizada', 'Legalizada'), ('Rechazada', 'Rechazada'), ('Anulada', 'Anulada')], default='Prematricula', max_length=20),
        ),
    ]
