# Generated by Django 5.2.14 on 2026-06-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0003_matricula_codigo_unico_matricula_creado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='exceder_cupo_autorizado',
            field=models.BooleanField(default=False),
        ),
    ]
