# Generated by Django 5.2.14 on 2026-06-20 19:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0004_matricula_exceder_cupo_autorizado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='anio_lectivo_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='matriculaperiodo',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='matricularequisito',
            name='es_obligatorio',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='promedio_anual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='matricularequisito',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='requisito',
            name='observacion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'Legalizada')), fields=('estudiante_id', 'anio_lectivo_id'), name='uniq_estudiante_anio_lectivo_legalizado', violation_error_message='El estudiante ya tiene una matrícula legalizada en este año lectivo.'),
        ),
    ]
