# Generated by Django 5.2.14 on 2026-06-20 19:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0005_matricula_anio_lectivo_id_matricula_observaciones_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='institucion_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterConstraint(
            model_name='matricula',
            name='uniq_estudiante_anio_lectivo_legalizado',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'Legalizada')), fields=('estudiante_id', 'anio_lectivo_id'), name='uniq_estudiante_anio_lectivo_legalizado', violation_error_message='El estudiante ya tiene una matricula legalizada en este ano lectivo.'),
        ),
    ]
