# Generated by Django 6.0.5 on 2026-06-22 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actoresAcademicos', '0005_remove_docente_correo_institucional_and_more'),
        ('institucion', '0003_institucion_es_activo'),
        ('matricula', '0006_matricula_institucion_id_and_more'),
        ('planificacion', '0007_paralelo_docentetutor_paralelo_jornada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Create new Representante model
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, default='', max_length=15)),
                ('parentesco', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Representante',
                'verbose_name_plural': 'Representantes',
                'db_table': 'matricula_representante',
            },
        ),
        # 2. Remove old IntegerField columns BEFORE adding FK columns with same _id names
        migrations.RemoveConstraint(
            model_name='matricula',
            name='uniq_estudiante_anio_lectivo_legalizado',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='anio_lectivo_id',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='estudiante_id',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='institucion_id',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='paralelo_id',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='representante_id',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='secretaria_id',
        ),
        migrations.RemoveField(
            model_name='matriculaperiodo',
            name='anio_lectivo_id',
        ),
        migrations.RemoveField(
            model_name='matriculaperiodo',
            name='educacion_nivel_id',
        ),
        migrations.RemoveField(
            model_name='matriculaperiodo',
            name='institucion_id',
        ),
        # 3. Add new FK columns
        migrations.AddField(
            model_name='matricula',
            name='anio_lectivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='planificacion.aniolectivo'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='actoresAcademicos.estudiante'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='institucion.institucion'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='paralelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='planificacion.paralelo'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='secretaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculas_gestionadas', to='actoresAcademicos.secretaria'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='representante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='matricula.representante'),
        ),
        migrations.AddField(
            model_name='matriculaperiodo',
            name='anio_lectivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periodos_matricula', to='planificacion.aniolectivo'),
        ),
        migrations.AddField(
            model_name='matriculaperiodo',
            name='educacion_nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periodos_matricula', to='planificacion.educacionnivel'),
        ),
        migrations.AddField(
            model_name='matriculaperiodo',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periodos_matricula', to='institucion.institucion'),
        ),
        migrations.AddField(
            model_name='matricularequisito',
            name='educacion_nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisitos_config', to='planificacion.educacionnivel'),
        ),
        migrations.AddField(
            model_name='matricularequisito',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisitos_config', to='institucion.institucion'),
        ),
        # 4. Re-add constraint with new FK field names
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'Legalizada')), fields=('estudiante', 'anio_lectivo'), name='uniq_estudiante_anio_lectivo_legalizado', violation_error_message='El estudiante ya tiene una matricula legalizada en este ano lectivo.'),
        ),
    ]
