# Generated by Django 6.0.5 on 2026-06-22 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0007_representante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='matriculaperiodo',
            name='requisitos',
        ),
        migrations.AddField(
            model_name='matricularequisito',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisitos_definidos', to='matricula.matriculaperiodo'),
        ),
    ]
