# Generated by Django 6.0.5 on 2026-06-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0008_eliminar_observaciones_m2m_y_agregar_periodo_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='rep_apellidos',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='matricula',
            name='rep_identificacion',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='matricula',
            name='rep_nombres',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='matricula',
            name='rep_parentesco',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='matricula',
            name='rep_telefono',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
