# Generated by Django 6.0.5 on 2026-06-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0009_matricula_rep_apellidos_matricula_rep_identificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='asp_apellidos',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='matricula',
            name='asp_correo_personal',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='matricula',
            name='asp_fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='asp_nombres',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
