# Generated by Django 5.2.14 on 2026-06-24 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actoresAcademicos', '0006_mover_direccion_domicilio_a_hijos'),
        ('matricula', '0010_matricula_asp_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisito',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitos_revisados', to='actoresAcademicos.cuenta'),
        ),
    ]
