# Generated by Django 5.2.14 on 2026-06-24 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actoresAcademicos', '0006_mover_direccion_domicilio_a_hijos'),
        ('matricula', '0011_alter_requisito_revisado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculas_creadas', to='actoresAcademicos.cuenta'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='legalizada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculas_legalizadas', to='actoresAcademicos.cuenta'),
        ),
    ]
