# Generated by Django 6.0.5 on 2026-06-24 21:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0012_alter_matricula_creado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisito',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='matricula/requisitos/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
