# Generated by Django 6.0.5 on 2026-08-21 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0013_alter_requisito_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculaperiodo',
            name='educacion_nivel',
            field=models.CharField(blank=True, choices=[('Educación Inicial', 'INICIAL'), ('Educación General Básica', 'EGB'), ('Bachillerato', 'BACHILLERATO')], help_text='Nivel educativo del periodo de matrícula', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='matricularequisito',
            name='educacion_nivel',
            field=models.CharField(blank=True, choices=[('Educación Inicial', 'INICIAL'), ('Educación General Básica', 'EGB'), ('Bachillerato', 'BACHILLERATO')], help_text='Nivel educativo del requisito', max_length=30, null=True),
        ),
    ]
