# Generated by Django 6.0.5 on 2026-09-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0014_alter_matriculaperiodo_educacion_nivel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='asp_celular',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='matricula',
            name='asp_identificacion',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='matricula',
            name='asp_tipo_identificacion',
            field=models.CharField(blank=True, default='CEDULA', max_length=20),
        ),
    ]
