# Generated by Django 5.2.14 on 2026-05-26 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matricula', '0002_alter_matricula_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=500)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('Programado', 'Programado'), ('En curso', 'En curso'), ('Finalizado', 'Finalizado')], default='Programado', max_length=20)),
                ('distributivo_asignatura_id', models.IntegerField()),
                ('horario_id', models.IntegerField(blank=True, null=True)),
                ('distributivo_evaluacion_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
                'db_table': 'clase',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(blank=True, max_length=500)),
                ('notificar', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('Asistencia', 'Asistencia'), ('Inasistencia', 'Inasistencia'), ('Justificado', 'Justificado'), ('Atrasado', 'Atrasado')], default='Asistencia', max_length=20)),
                ('matricula', models.ForeignKey(db_column='matricula_id', on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='matricula.matricula')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='asistencia.clase')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'db_table': 'asistencia',
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='asistencia.asistencia')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'db_table': 'incidencia',
            },
        ),
    ]
