# Generated by Django 6.0.5 on 2026-05-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gobernanza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='gobernanza/documentos/')),
                ('vigenteDesde', models.DateTimeField()),
                ('vigenteHasta', models.DateTimeField()),
                ('gobernanzaTipo', models.CharField(choices=[('PROYECTO_EDUCATIVO', 'Proyecto Educativo Institucional'), ('CODIGO_CONVIVENCIA', 'Código de Convivencia'), ('PLAN_GESTION_RIESGO', 'Plan de Gestión de Riesgo')], max_length=50)),
            ],
            options={
                'verbose_name': 'Gobernanza',
                'verbose_name_plural': 'Gobernanza',
            },
        ),
    ]
