# Generated by Django 6.0.5 on 2026-06-20 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0002_institucion_direccion'),
        ('planificacion', '0003_remove_educacionnivel_nivel_educacionsubnivel_nivel'),
        ('gobernanza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gobernanza',
            name='es_activo',
            field=models.BooleanField(default=True, verbose_name='¿Está activo?'),
        ),
        migrations.AddField(
            model_name='gobernanza',
            name='institucion',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='gobernanzas',
                to='institucion.institucion',
                verbose_name='Institución',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gobernanza',
            name='anioLectivo',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='gobernanzas',
                to='planificacion.aniolectivo',
                verbose_name='Año Lectivo',
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='gobernanza',
            unique_together={('institucion', 'anioLectivo', 'gobernanzaTipo')},
        ),
    ]
