# Generated by Django 6.0.5 on 2026-06-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobernanza', '0002_gobernanza_relaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gobernanza',
            name='es_activo',
            field=models.BooleanField(default=True),
        ),
    ]
