# Generated by Django 6.0.5 on 2026-05-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distributivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente', models.CharField(max_length=100)),
                ('materia', models.CharField(max_length=100)),
                ('paralelo', models.CharField(max_length=10)),
                ('horas', models.IntegerField()),
            ],
        ),
    ]
