# Generated by Django 6.0.5 on 2026-05-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributivo',
            name='horario',
            field=models.CharField(default='Pendiente', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='distributivo',
            name='horas',
            field=models.PositiveIntegerField(),
        ),
    ]
