# Generated by Django 6.0.5 on 2026-05-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributivos', '0002_distributivo_horario_alter_distributivo_horas'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='distributivo',
            constraint=models.UniqueConstraint(fields=('docente', 'horario'), name='unique_docente_horario'),
        ),
    ]
