# Generated by Django 5.2.13 on 2026-05-24 05:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributivos', '0004_distributivo_created_at_distributivo_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributivoAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura_ofertada_referencia', models.CharField(help_text='TODO: replace with FK to AsignaturaOfertada when module exists.', max_length=150)),
                ('observacion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Distributivo Asignatura',
                'verbose_name_plural': 'Distributivos Asignatura',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('observacion', models.TextField(blank=True)),
                ('tipo_horario', models.CharField(choices=[('CLASE', 'Clase'), ('COMPLEMENTARIA', 'Complementaria')], max_length=20)),
                ('dia_semana', models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miercoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='JornadaHora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jornada Hora',
                'verbose_name_plural': 'Jornadas Hora',
                'ordering': ['hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PlanificacionCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='planificaciones_curriculares/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('observacion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('POR_APROBAR', 'Por aprobar'), ('APROBADO', 'Aprobado')], default='BORRADOR', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Planificacion Curricular',
                'verbose_name_plural': 'Planificaciones Curriculares',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanificacionCurricularHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado_anterior', models.CharField(choices=[('BORRADOR', 'Borrador'), ('POR_APROBAR', 'Por aprobar'), ('APROBADO', 'Aprobado')], max_length=20)),
                ('estado_actual', models.CharField(choices=[('BORRADOR', 'Borrador'), ('POR_APROBAR', 'Por aprobar'), ('APROBADO', 'Aprobado')], max_length=20)),
                ('observacion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Planificacion Curricular Historial',
                'verbose_name_plural': 'Planificaciones Curriculares Historial',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AlterModelOptions(
            name='distributivo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Distributivo', 'verbose_name_plural': 'Distributivos'},
        ),
        migrations.RemoveConstraint(
            model_name='distributivo',
            name='unique_docente_horario',
        ),
        migrations.RemoveField(
            model_name='distributivo',
            name='docente',
        ),
        migrations.RemoveField(
            model_name='distributivo',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='distributivo',
            name='horas',
        ),
        migrations.RemoveField(
            model_name='distributivo',
            name='materia',
        ),
        migrations.RemoveField(
            model_name='distributivo',
            name='paralelo',
        ),
        migrations.AddField(
            model_name='distributivo',
            name='anio_lectivo_referencia',
            field=models.CharField(blank=True, help_text='TODO: replace with FK to AñoLectivo when module exists.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='distributivo',
            name='docente_referencia',
            field=models.CharField(blank=True, help_text='TODO: replace with FK to Docente when module exists.', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='distributivo',
            name='observacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='distributivoasignatura',
            name='distributivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='distributivos.distributivo'),
        ),
        migrations.AddField(
            model_name='horario',
            name='distributivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='distributivos.distributivo'),
        ),
        migrations.AddField(
            model_name='horario',
            name='distributivo_asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='distributivos.distributivoasignatura'),
        ),
        migrations.AddField(
            model_name='horario',
            name='jornada_hora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horarios', to='distributivos.jornadahora'),
        ),
        migrations.AddField(
            model_name='planificacioncurricular',
            name='distributivo_asignatura',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planificacion_curricular', to='distributivos.distributivoasignatura'),
        ),
        migrations.AddField(
            model_name='planificacioncurricularhistorial',
            name='planificacion_curricular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='distributivos.planificacioncurricular'),
        ),
    ]
