# Generated by Django 6.0.5 on 2026-06-22 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributivos', '0007_replace_temporal_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributivoasignatura',
            name='distributivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='distributivos.distributivo'),
        ),
    ]
