# Generated by Django 6.0.5 on 2026-06-23 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributivos', '0008_alter_distributivoasignatura_distributivo'),
        ('planificacion', '0007_paralelo_docentetutor_paralelo_jornada'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributivoasignatura',
            name='paralelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distributivos_asignatura', to='planificacion.paralelo'),
        ),
        migrations.AddConstraint(
            model_name='distributivoasignatura',
            constraint=models.UniqueConstraint(fields=('distributivo', 'asignatura_ofertada', 'paralelo'), name='unique_distributivo_asignatura_paralelo'),
        ),
    ]
