# Generated by Django 6.0.5 on 2026-06-25 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributivos', '0009_distributivoasignatura_paralelo_and_more'),
        ('planificacion', '0008_aniolectivo_institucion'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miercoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes')], max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('orden', models.IntegerField(help_text='Número de orden del bloque (1ra hora, 2da hora...)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jornada_hora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bloques_horarios', to='distributivos.jornadahora')),
                ('paralelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bloques_horarios', to='planificacion.paralelo')),
            ],
            options={
                'verbose_name': 'Bloque Horario',
                'verbose_name_plural': 'Bloques Horarios',
                'ordering': ['paralelo', 'dia_semana', 'orden'],
            },
        ),
        migrations.AddField(
            model_name='horario',
            name='bloque_horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='horarios_asignados', to='distributivos.bloquehorario'),
        ),
        migrations.AddConstraint(
            model_name='bloquehorario',
            constraint=models.UniqueConstraint(fields=('paralelo', 'dia_semana', 'hora_inicio'), name='unique_bloque_paralelo'),
        ),
    ]
